### ISSUE TITLE
Issue with `pandas`

### ISSUE THREAD

**Issue by ericmjl** [pympler/pympler#39]
Hi guys! Just wanted to report an unexpected bug. When I load `pandas`, `pympler` will throw the following error:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-3-a6233df5005b> in <module>()
         12 get_ipython().magic('load_ext autoreload')
         13 get_ipython().magic('autoreload 2')
    ---> 14 tr = tracker.SummaryTracker()

    /Users/ericmjl/anaconda/lib/python3.5/site-packages/pympler/tracker.py in __init__(self, ignore_self)
         43         ignore_self -- summaries managed by this object will be ignored.
         44         """
    ---> 45         self.s0 = summary.summarize(muppy.get_objects())
         46         self.summaries = {}
         47         self.ignore_self = ignore_self

    /Users/ericmjl/anaconda/lib/python3.5/site-packages/pympler/summary.py in summarize(objects)
        129         else:
        130             count[otype] = 1
    --> 131             total_size[otype] = _getsizeof(o)
        132     rows = []
        133     for otype in count:

    /Users/ericmjl/anaconda/lib/python3.5/site-packages/pandas/core/base.py in __sizeof__(self)
        128         # no memory_usage attribute, so fall back to
        129         # object's 'sizeof'
    --> 130         return super(self, PandasObject).__sizeof__()
        131 
        132 

    TypeError: must be type, not FrozenList

I figured this out by progressively uncommenting my import statements (from the bottom-up), and running my code in a Jupyter notebook.

    # from autograd import grad

    # import autograd.numpy as np
    # import pickle as pkl
    # import json
    import pandas as pd
    import matplotlib.pyplot as plt

    from pympler import muppy, summary, tracker

    %matplotlib inline
    %load_ext autoreload
    %autoreload 2
    tr = tracker.SummaryTracker()

In case it helps, my environment can be summarized as such:

- Python 3.5 (Anaconda distribution)
- full SciPy stack
- a lot of other packages
- `Pympler` 0.4.3

**Comment by gkunter** [comment]
This is actually a bug in Pandas and not in pympler. It was resolved by [this commit](https://github.com/pydata/pandas/pull/12924), so the issue will probably disappear with future versions of Pandas.

**Comment by DanielsWrath** [comment]
I still have this problem in this code:

```
from pympler import muppy, summary
objects = muppy.get_objects()
sum = summary.summarize(objects)
summary.summarize(sum)
```

It gives the following error:
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1578, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/DanielHaitink/PycharmProjects/PreFin/iterator.py", line 46, in <module>
    model.train(source)
  File "/Users/DanielHaitink/PycharmProjects/PreFin/model.py", line 159, in train
    self.__create_training_data__(self.labeled_data)
  File "/Users/DanielHaitink/PycharmProjects/PreFin/model.py", line 43, in __create_training_data__
    ['Label'])
  File "/Users/DanielHaitink/PycharmProjects/PreFin/utilities/lstm_training_data.py", line 19, in get_training_data
    sum = summary.summarize(objects)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pympler/summary.py", line 126, in summarize
    total_size[otype] = getsizeof(o)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/base.py", line 130, in __sizeof__
    return super(self, PandasObject).__sizeof__()
TypeError: must be type, not FrozenList
```
